[package]
name = "ostralka-vsb-fei"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Roman Táborský <@Astra3>"]
license = "MIT AND MIT-0"
description = "Bachelor's and Master's thesis at the Faculty of Electrical Engineering and Computer Science of Vysoká škola Báňská - Technical University of Ostrava."

repository = "https://github.com/Astra3/Typst-thesis-template-for-VSB"
keywords = ["VŠB", "VŠB-TUO", "thesis", "FEI", "bachelor", "master"]
compiler = "0.13.0"
categories = ["layout", "thesis"]
disciplines = ["computer-science", "engineering"]

exclude = ["format.sh"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.webp"

