[conf]
default-lang = "cs"

[lang.en]
# outlines
outline-images = "List of Figures"
outline-tables = "List of Tables"
outline-raw = "List of Source Code Listings"
outline-abbr = "List of symbols and abbreviations"

# titles
bachelor-thesis = "Bachelor thesis"
bachelor-practice = "Bachelor professional practice"
master-thesis = "Master thesis"
phd-thesis = "PhD thesis"
semestral-project = "Semestral project"

# misc
supervisor = "Supervisor:"
acknowledgment= "Acknowledgment"
assignment-heading = "Thesis assignment"

[lang.cs]
#outlines
outline-images = "Seznam obrázků"
outline-tables = "Seznam tabulek"
outline-raw = "Seznam výpisů zdrojového kódu"
outline-abbr = "Seznam použitých zkratek a symbolů"

# titles
bachelor-thesis = "Bakalářská práce"
bachelor-practice = "Bakalářská praxe"
master-thesis = "Diplomová práce"
phd-thesis = "Disertační práce"
semestral-project = "Semestrální projekt"

# misc
supervisor = "Vedoucí práce:"
acknowledgment= "Poděkování"
assignment-heading = "Zadání kvalifikační práce"
